#!/usr/bin/bash
oc new-project test 2>/dev/null
cp py-gunicorn/Dockerfile.server py-gunicorn/Dockerfile
oc new-build --strategy docker --binary --docker-image=python:alpine --name hello-mytls-server
oc start-build hello-mytls-server --from-dir py-gunicorn/ --follow
oc create secret generic hello-mytls-server --from-file appcerts/root.crt --from-file appcerts/server/site.crt --from-file appcerts/server/site.key
oc new-app hello-mytls-server
oc set volume dc/hello-mytls-server --add --type secret --mount-path /var/run/autocert.step.sm/ --secret-name hello-mytls-server --name certificates

# Build and deploy the client
cp py-gunicorn/Dockerfile.client py-gunicorn/Dockerfile
oc new-build --strategy docker --binary --docker-image=python:alpine --name hello-mytls-client
oc start-build hello-mytls-client --from-dir py-gunicorn/ --follow
oc create secret generic hello-mytls-client --from-file appcerts/root.crt --from-file appcerts/client/site.crt --from-file appcerts/client/site.key
oc new-app hello-mytls-client
oc set volume dc/hello-mytls-client --add --type secret --mount-path /var/run/autocert.step.sm/ --secret-name hello-mytls-client --name certificates
oc set env dc/hello-mytls-client --overwrite HELLO_MTLS_URL=https://hello-mytls-server.test.svc.cluster.local:8443
