#!/usr/bin/bash

# Configuration
CERT_PATH=./appcerts
PUBLIC_HOSTNAME=hello-mytls-server.test.svc.cluster.local

# Make a directory for certificates, if missing
if [ ! -e "${CERT_PATH}" ]; then
  mkdir -p ${CERT_PATH}/{server,client}
fi

# Create the CA and intermediate pair
if [ ! -e ${CERT_PATH}/custom-ca.key ]; then
  # Create the CA certificate
  openssl req -new -newkey rsa:2048 -days 3652 -nodes -x509 \
    -keyout ${CERT_PATH}/custom-ca.key \
    -out ${CERT_PATH}/custom-ca.crt \
    -subj '/C=US/ST=GA/L=Atlanta/O=VMware/OU=Lab/CN=OpenShiftHappens CA'
  # Create the intermediate certificate request
  openssl req -new -newkey rsa:2048 -days 1826 -nodes \
    -keyout ${CERT_PATH}/custom-intermediate.key \
    -out ${CERT_PATH}/custom-intermediate.csr \
    -subj '/C=US/ST=GA/L=Atlanta/O=VMware/OU=Lab/CN=OpenShiftHappens Intermediate CA'
  # Create the intermediate certificate
  openssl x509 -req -days 1826 -CAcreateserial \
    -extensions v3_intermediate_ca \
    -CA ${CERT_PATH}/custom-ca.crt \
    -CAkey ${CERT_PATH}/custom-ca.key \
    -in ${CERT_PATH}/custom-intermediate.csr \
    -out ${CERT_PATH}/custom-intermediate.crt
  # Concatenate the certificates into a single file
  cat ${CERT_PATH}/custom-ca.crt ${CERT_PATH}/custom-intermediate.crt >${CERT_PATH}/root.crt
fi

# Generate certificate request and put it in ${CERT_PATH}/
openssl req -new -newkey rsa:2048 -days 365 -nodes \
  -reqexts SAN -config <(cat /etc/pki/tls/openssl.cnf <(printf "[SAN]\nsubjectAltName=DNS:${PUBLIC_HOSTNAME}")) \
  -keyout ${CERT_PATH}/server/site.key \
  -out ${CERT_PATH}/server/site.csr \
  -subj '/C=US/ST=GA/L=Atlanta/O=VMware/OU=Lab/CN='${PUBLIC_HOSTNAME}

# Sign the certificate with the CA and put it in ${CERT_PATH}/
openssl x509 -req -days 365 -CAcreateserial \
  -CA ${CERT_PATH}/custom-ca.crt \
  -CAkey ${CERT_PATH}/custom-ca.key \
  -extfile v3.ext \
  -in ${CERT_PATH}/server/site.csr \
  -out ${CERT_PATH}/server/site.crt

# Generate certificate request and put it in ${CERT_PATH}/
openssl req -new -newkey rsa:2048 -days 365 -nodes \
  -keyout ${CERT_PATH}/client/site.key \
  -out ${CERT_PATH}/client/site.csr \
  -subj '/C=US/ST=GA/L=Atlanta/O=VMware/OU=Lab/CN=myapp@openshifthappens.com'

# Sign the certificate with the CA and put it in ${CERT_PATH}/
openssl x509 -req -days 365 -CAcreateserial \
  -CA ${CERT_PATH}/custom-ca.crt \
  -CAkey ${CERT_PATH}/custom-ca.key \
  -in ${CERT_PATH}/client/site.csr \
  -out ${CERT_PATH}/client/site.crt
